### ISSUE TITLE
Support Availablity

### ISSUE THREAD

**Issue by pascaldekloe** [optiopay/kafka#119]
The client looks nice and promising. I would like to bring the client to the next level with patches, alas no response. Jeremy said he's on leave, and Max won't respond on LinkedIn. What to do?

Does Optiopay intend to maintain this project or is this repository more of a "take as is" publication?

**Comment by dgellow** [comment]
Hi Pascal. Sorry for the late response, let me ask internally to see with others how they want to handle this project.

**Comment by pascaldekloe** [comment]
Two weeks of no response is an answer by itself. I've started my own for now.

**Comment by dgellow** [comment]
Ok, all the best!

I'm closing this issue if you don't mind.

**Comment by pascaldekloe** [comment]
Thanks for picking this up @dgellow. 👍 Feel free to cherry pick from https://github.com/pascaldekloe/kafka if there's anything you like.
