### ISSUE TITLE
Cache connections used by producer

### ISSUE THREAD

**Issue by husio** [optiopay/kafka#12]
Currently, whenever producer writes message, broker is asked for leader connection for given destination.
It is common to use producer to always write to the same destination (one or more), therefore producer is always asking broker about the same leader connection. Instead, producer could cache connection between calls.

This means that in case of leader change, cached connection will return error. In such case, producer should understand `ErrNotLeaderForPartition` error, flush connections cache and retry.

**Comment by cespare** [comment]
To be clear, this is an optimization to reduce mutex contention on the broker's mutex, right?

When I read this issue I thought it meant that this library was issuing a metadata API call to the broker for every Produce() call, but tracing the code I see that the metadata is definitely cached.

**Comment by husio** [comment]
Yes. Right now, every single function call use `muLeaderConnection` to get the right connection. It's nice abstraction, because producer binds to configuration, not connection. But in real life, you want to use single producer to produce (most of the time) to the same destination all the time.

Caching connections on producer might be improvement. But first this needs a benchmark to show if the complexity is worth it.

**Comment by cespare** [comment]
I think for many high-performance use cases it might not matter much, since usually doing high throughput into Kafka involves doing big batches (so the number of Produce() calls isn't that big -- each one might be sending 100 or 1000 messages.) That's what our use case is, at least.

**Comment by husio** [comment]
You are probably right, but there are still companies like Optiopay where we publish most of the time one message at a time :wink: I guess this is rare case, but it functionality is easily achievable, I would like to know what's possible benefit from it.

**Comment by cespare** [comment]
Not saying it's a bad idea, but I expect a little batching will greatly outweigh getting rid of the lock contention here. If you're sending so few messages that you can't batch, then probably the mutex overhead isn't noticeable.

**Comment by husio** [comment]
Unless single connection is used for many producers, this does not bring any change.
