### ISSUE TITLE
confluent-kafka-go - Got JoinGroup failed: Local: Required feature not supported by broker

### ISSUE THREAD

**Issue by amgonencl** [optiopay/kafka#123]
I get the following error ```2019/10/08 14:36:38 unknown request: 18```

it seems to be coming from handleClient

**Comment by e-max** [comment]
Are talking about the `kafkatest` right?   It's strange, do you use the latest master?  We added a support for this request type recently.     Anyway,  `kafkatest` were a test tool which we used during development.  We don't encourage to use this tool and don't guarantee that it is in a working state.

**Comment by amgonencl** [comment]
1. yes it is kafkatest 
2. I want to use it to unit test  my code
3. I'm using `	github.com/optiopay/kafka v2.0.7+incompatible`
I'll check if this is the lastest

**Comment by amgonencl** [comment]
I've pull master version . the message disapper thanks . but now I get new problem :
%5|1570642331.592|MAXPOLL|rdkafka#consumer-1| [thrd:main]: GroupCoordinator/0: Broker does not support KIP-62 (requires Apache Kafka >= v0.10.1.0): consumer configuration `max.poll.interval.ms` (300000) is effectively limited by `session.timeout.ms` (10000) with this broker version

**Comment by e-max** [comment]
Yes, that is exactly what I meant.   `kafkatest` supports only the simplest possible version of kafka  protocol.  Basically just enough to put message in topic and then read it.    It definitely doesn't support Groups and auto sharding.

**Comment by dgellow** [comment]
As explained by @e-max, `kafkatest` only covers a minimal set of features, and isn't intended for general use. I'm closing this ticket.
