### ISSUE TITLE
Consumer doesn't transparently fail over when the leader changes

### ISSUE THREAD

**Issue by cespare** [optiopay/kafka#27]
I meant to send a PR but I haven't gotten to the bottom of this yet and so I wanted to at least write down the problem I'm seeing.

When I'm producing messages to a cluster of several nodes and I kill one of the kafka brokers (the leader for the partition I'm writing to), the producer sees the dead connection, reloads metadata, and then starts sending to the new leader without any trouble.

If I have a consumer pulling from the same partition, when the leader it's reading from goes away, the consumer keeps trying to reconnect and eventually gives back an error to the user. It doesn't ever recover on its own.

I would expect that both the producer and consumer would automatically fail over when the leader that they're talking to goes away.

**Comment by husio** [comment]
I think this is related to #26 and should be solved with refactored network errors handling.

**Comment by cespare** [comment]
OK, I've found at least two code paths through the consumer's retry loop that can continually error out talking to a bad broker (either a broker that is down or a broker that isn't the leader for the partition) and never refresh metadata to learn the new broker.

Sending fixes shortly.
