### ISSUE TITLE
Distributed Consumer?

### ISSUE THREAD

**Issue by sixtus** [optiopay/kafka#36]
It looks like https://godoc.org/github.com/optiopay/kafka#example-OffsetCoordinator allows for consumer groups, but I fail to see how the assignment of a partition to a consumer in a distributed consumer environment should work.

**Comment by alpe** [comment]
Not sure if I understand your question correct. Are you looking for some  [High level consumer](https://cwiki.apache.org/confluence/display/KAFKA/Consumer+Group+Example) functionality to manage partitions and sync offsets for a group?
It's not available in this codebase. You'd need to implement it yourself.

**Comment by husio** [comment]
@sixtus did @alpe answered your question?

**Comment by liquidm-tech** [comment]
Well, yes and no.

I am looking for a high level consumer in go (sarama cluster is too buggy) and was hoping, I can base it on your lib.

So the true answer to my question will be #39 - looking forward to it ;)

**Comment by sixtus** [comment]
Always check your logged-in user first :)

**Comment by husio** [comment]
I'm closing this issue then. Any further progress will be described in #39 

I don't think we (optiopay company) will contribute to this anytime soon though, because we're on tight schedule and we don't need this functionality.

**Comment by zorkian** [comment]
I'm working on a distributed consumer library built on top of this client: https://github.com/zorkian/marshal

We're still in the pre-Alpha phase, it's not yet ready for production use. Tests pass but that doesn't mean much yet. Anyway, review/feedback is welcome, although you might also wait a week or two until we get to the point where it's apparently stable.
