### ISSUE TITLE
UknownTopic Or Partition

### ISSUE THREAD

**Issue by PragmaticCypher** [optiopay/kafka#4]
Would it be possible to have this error report which topic/partition in the error?

proto/errors.go:	ErrUnknownTopicOrPartition = &KafkaError{3, "unknown topic or partition"}

**Comment by husio** [comment]
Not without drawback. All standard errors are defined in https://github.com/optiopay/kafka/blob/master/proto/errors.go#L11 and because of this you can compare them. If I would build custom error with topic/partition information, there would be no chance to compare it.
